workflows:
  ionic-android-apk:
    name: Ionic Android APK
    max_build_duration: 60

    environment:
      node: 24       # <-- changer ici
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
