workflows:
  ionic-android-apk:
    name: Ionic Android APK
    max_build_duration: 68

    environment:
      node: 20
      java: 21

    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install @capacitor/cli @capacitor/core

      - name: Build Ionic
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync android

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleDebug

    artifacts:
      - android/app/build/outputs/apk/debug/app-debug.apk
